export const authTypes = {
	AUTH: 'AUTH',
	AUTH_ADMIN: 'AUTH_ADMIN',
	REFRESH_TOKEN: 'REFRESH_TOKEN',
	REFRESH_TOKEN_ADMIN: 'REFRESH_TOKEN_ADMIN',
	REGISTER_REQUEST: 'REGISTER_REQUEST',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	REGISTER_FAILURE: 'REGISTER_FAILURE',
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGOUT_REQUEST: 'LOGOUT_REQUEST',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_FAILURE: 'LOGOUT_FAILURE',
	LOGOUT_ADMIN_REQUEST: 'LOGOUT_ADMIN_REQUEST',
	LOGOUT_ADMIN_SUCCESS: 'LOGOUT_ADMIN_SUCCESS',
	LOGOUT_ADMIN_FAILURE: 'LOGOUT_ADMIN_FAILURE'
}

export const uiTypes = {
	SHOW_SNACKBAR: 'SHOW_SNACKBAR',
	HIDE_SNACKBAR: 'HIDE_SNACKBAR',
	SHOW_BACKDROP: 'SHOW_BACKDROP',
	HIDE_BACKDROP: 'HIDE_BACKDROP'
}

export const userTypes = {
	GET_USERS: 'GET_USERS',
	ADD_USER: 'ADD_USER',
	UPDATE_USER: 'UPDATE_USER',
	DELETE_USER: 'DELETE_USER'
}

export const categoryTypes = {
	GET_CATEGORIES: 'GET_CATEGORIES'
}

export const productTypes = {
	GET_PRODUCTS: 'GET_PRODUCTS'
}