export const authTypes = {
	AUTH: 'AUTH',
	AUTH_ADMIN: 'AUTH_ADMIN',
	REGISTER_REQUEST: 'REGISTER_REQUEST',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	REGISTER_FAILURE: 'REGISTER_FAILURE',
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGOUT_REQUEST: 'LOGOUT_REQUEST',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_FAILURE: 'LOGOUT_FAILURE',
	LOGOUT_ADMIN_REQUEST: 'LOGOUT_ADMIN_REQUEST',
	LOGOUT_ADMIN_SUCCESS: 'LOGOUT_ADMIN_SUCCESS',
	LOGOUT_ADMIN_FAILURE: 'LOGOUT_ADMIN_FAILURE'
}

export const uiTypes = {
	SHOW_SNACKBAR: 'SHOW_SNACKBAR',
	HIDE_SNACKBAR: 'HIDE_SNACKBAR',
	SHOW_BACKDROP: 'SHOW_BACKDROP',
	HIDE_BACKDROP: 'HIDE_BACKDROP'
}